CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -Werror

all: task1 task3

task1: task1.cpp
	$(CXX) $(CXXFLAGS) task1.cpp -o task1

task3: task3.cpp
	$(CXX) $(CXXFLAGS) task3.cpp -o task3

clean:
	rm -f task1
	rm -f task3
